language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

install: [[ "$TRAVIS_RUST_VERSION" != "nightly" ]] || cargo install clippy
script:
  - [[ "$TRAVIS_RUST_VERSION" != "nightly" ]] || cargo clippy
  - cargo test --verbose
